# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html
# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Kotlin code style for this project: "official" or "obsolete":
kotlin.code.style=official

# Fix for "Using kotlin.sourceSets DSL to add Kotlin sources is not allowed with built-in Kotlin"
# this warning appears because some plugins still use Kotlin source sets and not android source sets in the transitioning phase. can be removed in the future
android.disallowKotlinSourceSets=false
