package de.marquisproject.finotes.data.notes.model

import androidx.annotation.Keep
import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

@Keep
enum class NoteStatus {
    ACTIVE,
    ARCHIVED,
    BINNED
}

/**
 * TODO() Support full text search for notes using the Fts3 or Fts4 library.
 *
 * @param id unique identifier for the note. Defaults to null and will be auto generated by the database.
 * @param title title of the note
 * @param body content of the note
 * @param category category of the note
 * @param isPinned boolean indicating if the note is pinned
 * @param dateCreated timestamp of the creation date as Long
 * @param lastModified timestamp of the last modification date as Long
 * @param noteStatus status of the note as NoteStatus so either ACTIVE, ARCHIVED or BINNED
 * @param needsSync boolean indicating if the note needs to be synced to the server
 * @param remoteId unique identifier for the note on the server
 *
 * The entity has an index now for the noteStatus which means that the database will automatically
 * store and update an index of the noteStatus for every note which will make accesses for
 * the noteStatus faster.
 *
 * Important: If the type of column is changed, the App will crash because the db still has the old type.
 * Therefore, the App has to be uninstalled and reinstalled to recreate the db. Or a migration has to be created.
 */
@Entity(tableName = Note.TABLE_NAME, indices = [Index(value = [Note.COLUMN_NOTE_STATUS])])
data class Note(
    @PrimaryKey(autoGenerate = true) val id: Long? = null,
    @ColumnInfo(name = COLUMN_TITLE) val title: String = "",
    @ColumnInfo(name = COLUMN_BODY) val body: String = "",
    @ColumnInfo(name = COLUMN_CATEGORY) val category: Long = 0,
    @ColumnInfo(name = COLUMN_IS_PINNED) val isPinned: Boolean = false,
    @ColumnInfo(name = COLUMN_DATE_CREATED) val dateCreated: Long = System.currentTimeMillis(),
    @ColumnInfo(name = COLUMN_LAST_MODIFIED) val lastModified: Long = System.currentTimeMillis(),
    @ColumnInfo(name = COLUMN_NOTE_STATUS) val noteStatus: NoteStatus = NoteStatus.ACTIVE,
    @ColumnInfo(name = COLUMN_NEEDS_SYNC) val needsSync: Boolean = false,
    @ColumnInfo(name = COLUMN_REMOTE_ID) val remoteId: Long? = null
) {
    companion object {
        const val TABLE_NAME = "notes_table"
        const val COLUMN_TITLE = "title"
        const val COLUMN_BODY = "body"
        const val COLUMN_CATEGORY = "category"
        const val COLUMN_IS_PINNED = "isPinned"
        const val COLUMN_DATE_CREATED = "dateCreated"
        const val COLUMN_LAST_MODIFIED = "lastModified"
        const val COLUMN_NOTE_STATUS = "noteStatus"
        const val COLUMN_NEEDS_SYNC = "needsSync"
        const val COLUMN_REMOTE_ID = "remoteId"
    }

    /**
     * This is used to mark the note as needing to be synced to the server.
     * @return Note with the needsSync field set to true and the lastModified field set to the current time.
     */
    fun prepareForUpdate(): Note {
        return this.copy(
            lastModified = System.currentTimeMillis(),
            needsSync = true
        )
    }

    /**
     * @return: true if the note has an id, false otherwise.
     */
    fun isExistingNote() : Boolean{
        return this.id != null
    }

    /**
     * @return: true if the note is new (null id) and has content, false otherwise.
     */
    fun isUnsavedNoteWithContent() : Boolean {
        return !this.isExistingNote() && (this.title.isNotBlank() || this.body.isNotBlank())
    }
}