package de.marquisproject.finotes.data.notes.sources

import de.marquisproject.finotes.data.notes.model.Note

import androidx.room.Dao
import androidx.room.Query
import androidx.room.Delete
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import kotlinx.coroutines.flow.Flow


@Dao
interface ArchiveDAO {
    /**
     * Insert a new note into the archive database. Return the autogenerated id of the new note.
     * @param note Note object to be inserted
     * @return Long id of the note (the new autogenerated id)
     */
    @Insert
    suspend fun insertNote(note: Note) : Long

    @Delete
    suspend fun deleteNote(note: Note)

    @Query("SELECT * FROM notes_table ORDER BY dateCreated DESC")
    fun getAllNotes(): Flow<List<Note>>

    @Query("SELECT * FROM notes_table WHERE id = :noteId")
    fun getNoteById(noteId: Long): Flow<Note>

    @Insert(onConflict = OnConflictStrategy.ABORT)
    fun insertListOfNotes(notes: List<Note>)
}