package de.marquisproject.finotes.data.notes.sources

import de.marquisproject.finotes.data.notes.model.Note

import androidx.room.Dao
import androidx.room.Query
import androidx.room.Delete
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.RawQuery
import androidx.room.Update
import androidx.sqlite.db.SimpleSQLiteQuery
import androidx.sqlite.db.SupportSQLiteQuery
import de.marquisproject.finotes.data.notes.model.NoteStatus
import kotlinx.coroutines.flow.Flow


@Dao
interface NoteDAO {
    /**
     * Insert a new note into the database. Return the autogenerated id of the new note.
     * Upsert is not used because if a potential note in the bin database is restored with a id that already exists in the notes database, the note would be overwritten.
     * Suspend is used because it is a coroutine function and we use it here because no data is returned.
     * @param note Note object to be upsert
     * @return Long id of the note (either the new autogenerated id or the id of the updated note)
     */
    @Insert
    suspend fun insertNote(note: Note): Long

    /**
     * Update an existing note in the database.
     * Suspend is used because it is a coroutine function and we use it here because no data is returned.
     * @param note Note object to be updated
     */
    @Update
    suspend fun updateNote(note: Note)

    /**
     * Delete a note from the database.
     * Suspend is used because it is a coroutine function and we use it here because no data is returned.
     * @param note Note object to be deleted
     */
    @Delete
    suspend fun deleteNote(note: Note)

    /**
     * Get a note by its id.
     * @param noteId Long id of the note to be fetched
     * @return Flow of Note object with the given id
     */
    @Query("SELECT * FROM ${Note.TABLE_NAME} WHERE id = :noteId")
    fun getNoteById(noteId: Long): Flow<Note>

    /**
     * With flow we get an observable which will notify us when there is a change in the database.
     * @return Flow of List of Notes ordered by lastEdited in descending order
     */
    @Query("SELECT * FROM ${Note.TABLE_NAME} ORDER BY isPinned DESC, dateCreated DESC")
    fun getAllNotes(): Flow<List<Note>>

    @Query("SELECT * FROM ${Note.TABLE_NAME} WHERE noteStatus = :noteStatus ORDER BY isPinned DESC, dateCreated DESC")
    fun getAllNotesByStatus(noteStatus: NoteStatus): Flow<List<Note>>

    /**
     *
     * @return Flow of List of Notes that match the query
     */
    @Query("""
    SELECT * FROM ${Note.TABLE_NAME}
    WHERE (:searchQuery IS NULL OR (title LIKE '%' || :searchQuery || '%' OR body LIKE '%' || :searchQuery || '%'))
    AND (:isPinned IS NULL OR isPinned = :isPinned)
    AND (:hasCategories = 0 OR category IN (:categories))
    AND (:noteStatus IS NULL OR noteStatus = :noteStatus)
    ORDER BY isPinned DESC, dateCreated DESC
""")
    fun getNotesWithQuery(
        searchQuery: String? = null,
        isPinned: Boolean? = null,
        categories: List<Long>? = null,
        noteStatus: NoteStatus? = null,
        // This parameter is used to conditionally enable/disable the category check
        hasCategories: Boolean = !categories.isNullOrEmpty()
    ): Flow<List<Note>>
}