package de.marquisproject.finotes.data.notes.sources

import de.marquisproject.finotes.data.notes.model.Note

import androidx.room.Dao
import androidx.room.Query
import androidx.room.Delete
import androidx.room.Insert
import androidx.room.Update
import de.marquisproject.finotes.data.notes.model.NoteStatus
import kotlinx.coroutines.flow.Flow


@Dao
interface NoteDAO {
    /**
     * Insert a new note into the database. Return the autogenerated id of the new note.
     * Upsert is not used because if a potential note in the bin database is restored with an id that already exists in the notes database, the note would be overwritten.
     * Suspend is used because it is a coroutine function, and we use it here because no data is returned.
     * @param note Note object to be inserted
     * @return Long id of the note (either the new autogenerated id or the id of the updated note)
     */
    @Insert
    suspend fun insertNote(note: Note): Long

    /**
     * Update multiple notes in the database in a single transaction.
     * Suspend is used because it is a coroutine function, and we use it here because no data is returned.
     * @param notes List of Note objects to be updated
     */
    @Update
    suspend fun updateNotes(notes: List<Note>)

    /**
     * Delete multiple notes in the database in a single transaction.
     * Suspend is used because it is a coroutine function, and we use it here because no data is returned.
     * @param note Note object to be deleted
     */
    @Delete
    suspend fun deleteNotes(note: List<Note>)

    /**
     * Get a note by its id.
     * @param noteId Long id of the note to be fetched
     * @return Flow of Note object with the given id
     */
    @Query("SELECT * FROM ${Note.TABLE_NAME} WHERE id = :noteId")
    fun getNoteById(noteId: Long): Flow<Note>

    /**
     * With flow, we get an observable which will notify us when there is a change in the database.
     * @return Flow of List of Notes ordered by lastEdited in descending order
     */
    @Query("SELECT * FROM ${Note.TABLE_NAME} ORDER BY isPinned DESC, dateCreated DESC")
    fun getAllNotes(): Flow<List<Note>>

    /**
     * Get all notes with a specific status.
     * @param noteStatus NoteStatus of the notes to be fetched
     * @return Flow of List of Notes ordered by lastEdited in descending order
     */
    @Query("SELECT * FROM ${Note.TABLE_NAME} WHERE noteStatus = :noteStatus ORDER BY isPinned DESC, dateCreated DESC")
    fun getAllNotesByStatus(noteStatus: NoteStatus): Flow<List<Note>>

    /**
     * Get all notes with a specific status.
     * @param searchQuery String to be searched in the title and body of the notes
     * @param isPinned Boolean to be searched in the isPinned column of the notes
     * @param categories List of Long ids of the categories to be searched in the category column of the notes
     * @param noteStatus NoteStatus of the notes to be fetched
     * @return Flow of List of Notes that match the query
     */
    @Query("""
    SELECT * FROM ${Note.TABLE_NAME}
    WHERE (:searchQuery IS NULL OR (title LIKE '%' || :searchQuery || '%' OR body LIKE '%' || :searchQuery || '%'))
    AND (:isPinned IS NULL OR isPinned = :isPinned)
    AND (:hasCategories = 0 OR category IN (:categories))
    AND (:noteStatus IS NULL OR noteStatus = :noteStatus)
    ORDER BY isPinned DESC, dateCreated DESC
""")
    fun getNotesWithQuery(
        searchQuery: String? = null,
        isPinned: Boolean? = null,
        categories: List<Long>? = null,
        noteStatus: NoteStatus? = null,
        // This parameter is used to conditionally enable/disable the category check
        hasCategories: Boolean = !categories.isNullOrEmpty()
    ): Flow<List<Note>>
}